# Configuração minimalista para evitar conflitos yarn/npm
services:
  - type: web
    name: calendario-frontend
    runtime: node 
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
